language: node_js
node_js:
  - "10"
sudo: false
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
install:
  - yarn install
script:
  - yarn test --coverage && cat ./coverage/lconv.info | ./node_modules/coveralls/bin/coveralls.js
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master